frameworkVersion: "3"
service: certificate-update-mailer

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  environment:
    PERSISTENCE_BUCKET: ${env:PERSISTENCE_BUCKET}
    FROM_EMAIL: ${env:FROM_EMAIL}
    TO_EMAILS: ${env:TO_EMAILS}

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  notifier:
    handler: bin/handler
    events:
      - schedule: cron(0 8 * * ? *) # Run every day at 0800 UTC
